spring.application.name=itam
server.port=8080

# ===============================
# FILE-BASED PERSISTENT DATABASE (H2)
# ===============================
spring.datasource.url=jdbc:h2:file:./data/itamdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# SECURITY CONFIGURATION
# ===============================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.config.import=optional:file:.env
jwt.secret=${JWT_SECRET}
